name: Generate Docs

on:
  push:
    paths:
      - "types/**"
  pull_request:
    paths:
      - "types/**"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  gdocs:
    uses: luamod/.github/.github/workflows/gdocs.yml@v1
    with:
      lua_version: "luajit"
      types_dir: types
      output_dir: docs/src/modules
      export_script: scripts/export.lua
      exclude: "mods.lua"
