name: Generate Docs

on:
  push:
    branches:
      - main
    paths:
      - "types/**/*.lua"
      - "scripts/gen-docs.lua"
  pull_request:
    paths:
      - "types/**/*.lua"
      - "scripts/gen-docs.lua"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: "5.4"
      - uses: leafo/gh-actions-luarocks@v6
      - name: Install dependencies
        run: luarocks install luafilesystem
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Generate docs
        run: lua scripts/gen-docs.lua
      - name: Format generated docs
        run: npx --yes prettier --write "docs/modules/**/*.md" "docs/.vitepress/**/*.mts"
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(docs): auto-generate docs"
          branch: main
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
