name: Prettier

on:
  push:
    branches:
      - main
    paths:
      - "**/*.ts"
      - "**/*.mts"
      - "**/*.yml"
      - "**/*.yaml"
      - ".github/workflows/prettier.yml"
  pull_request:
    paths:
      - "**/*.ts"
      - "**/*.mts"
      - "**/*.yml"
      - "**/*.yaml"
      - ".github/workflows/prettier.yml"

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Prettier check
        run: |
          npx --yes prettier --check .
