name: Tests

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "spec/**"
      - ".github/workflows/tests.yml"
  pull_request:
    paths:
      - "src/**"
      - "spec/**"
      - ".github/workflows/tests.yml"

jobs:
  busted:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lua-version: ["5.1", "5.2", "5.3", "5.4"]
    steps:
      - uses: actions/checkout@v6
      - uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: ${{ matrix.lua-version }}
      - uses: leafo/gh-actions-luarocks@v5
      - name: Install dependencies
        run: |
          luarocks install busted
          luarocks install luacheck
      - name: Run luacheck
        run: luacheck .
      - name: Run tests
        run: busted
